### ISSUE TITLE
Missing file CFacefile.cpp 

### ISSUE THREAD

**Issue by xMooobyx** [orbian/BMOS#1]
Hello I am in need of help. I ran cmake .. then make. This is where the issue started. The terminal says 
cmake ..No rule to make target 'CFaceFile.cpp', needed by 'CFaceFile.o'.  Stop . 
I am having a hard time finding the file. Much appreciated if you or someone can help.

**Comment by orbian** [comment]
Odd, there is no CFaceFile.cpp in this repository and there never was. The CMakeList file doesn't show any dependency on the fileeither. Did you pull directly from this repository?

**Comment by xMooobyx** [comment]
I downloaded BMOS-Main and unzipped it within BMO-Utils file to be able to perform cmake ..

**Comment by orbian** [comment]
Delete the makefile and run cmake again.

**Comment by xMooobyx** [comment]
I just did a flash on the sd card again and started from the very beginning and the problem went away. Very weird. Thanks for the help though!
