### ISSUE TITLE
What PI os was used?

### ISSUE THREAD

**Issue by Samistine** [orbian/BMOS#3]
Software: Debian GNU/Linux 11 (bullseye) raspberrypi 6.1.21-v8+ (Using latest 64-bit version from RPIs website.)
Hardware: I am using a RPI 3b+. 

I was able to get the main application running but it crashes when attempting to play videos.
None of the hardware buttons from the HAT appear to be working.

I assume multiple things are broken in the scripts running on this newer linux operating system. I had to manually do extra things to get the utilities installed. I.E. manually copy google translator script into the correct directory.

What OS version are you using that works?

Things are fine until I start clicking around, in these logs when I opened beemotes and clicked on one of the videos it locked up and then crashed.
Logs:
```
sam@raspberrypi:/home/pi/bmos $ /home/pi/bmos/bmos
INFO: Display #0: current display mode is 800x600px @ 60hz.
INFO: dispW: 800, dispH: 600
X connection to :0 broken (explicit kill or server shutdown).
Can't find config file.
Can't find joystick file. Using defaults
Cmd: /home/pi/bmos/scripts/getip.sh
ip: (REDACTED)

[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
bmos: ../../src/xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
bmos: ../../src/xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

**Comment by orbian** [comment]
The image used is the current RetroPie image built on Buster. Bullseye has removed omxplayer which is required for the videos. VLC might work but I found it glitchy. Plus, RetroPie uses a custom version of SDL2 which is required for the desktop. I'm not sure what they changed, but the desktop doesn't render correctly with the stock SDL2 libraries. Also, everything runs from the CLI, the X server should not be running.
