### ISSUE TITLE
Difficulties with BMOS installation

### ISSUE THREAD

**Issue by UNITY6z** [orbian/BMOS#4]
Hello,

I started to create a BMO but i have a problem with the insatllation of the program on my raspberry Pi 4.
I also installe all of the BMO-Utils project and now i started to install the BMOS but i dont find how to install it on my raspberry. I follow all the instructions but when i am on the BUILD part everything i do is not working. It doesnt find the Cmakelist.txt in the repertory and i don't no where i can pull it.

Someone can help me to resolve this problem pls ?

Thank you ;)

**Comment by orbian** [comment]
Post your build output log.

**Comment by UNITY6z** [comment]
Sorry im a begginer in program so i don't understand what do you mean by "build output log"

In the installation of BMOS i do all the INSTALL part with no problem but when i doing the build part i have this error : 

![image](https://github.com/BYOBMO/BMOS/assets/161239511/fc7d41cd-053b-40b6-aa1e-a4efd157e27a)

**Comment by orbian** [comment]
Did you clone the bmos repository? There should be a directory called bmos. You make the build folder inside of that directory.

**Comment by UNITY6z** [comment]
Yes i clone the bmos repository, but after making the build folder in the BMOS directory i have an error : 

![image](https://github.com/BYOBMO/BMOS/assets/161239511/b2705299-8966-4513-a926-1c89a5331dca)

I know that i do something wrong but i don't know where 😕

**Comment by orbian** [comment]
try using sudo. Looks like your login credentials don't give you access.
