### ISSUE TITLE
Problems with BMOS installation

### ISSUE THREAD

**Issue by AjTech1089** [orbian/BMOS#5]
Okay so I am trying to download the operating system for my BMO that I built, but the thing is I don't know how I can image the file onto the SD card because I usually use Raspberry Pi Imager to install the image onto the SD card, there is no way for me to download the image and only just the code for the BMOS. How do I install BMOS with my Raspberry Pi Imager?

**Comment by orbian** [comment]
You will have to follow the instructions for installing RetroPie from Pi Imager here:
https://retropie.org.uk/docs/First-Installation/

**Comment by AjTech1089** [comment]
So wait, BMOS is basically RetroPie but modified or it is its own operating system?

**Comment by AjTech1089** [comment]
And I said I am installing BMOS not RetroPie.
